Support SpongeAPI 7.1.0
prism/PrismSponge pull request #111
Opened 2018-10-06 21:53 UTC by LXGaming

### Changes
Updated Prism dependencies
Fixed Build issues

2018-10-06 23:04 UTC, viveleroi requested changes

2018-10-06 23:04 UTC, viveleroi commented on src/main/java/com/helion3/prism/api/records/BlockResult.java
>  import org.spongepowered.api.world.BlockChangeFlag;
I think this import is no longer used and can be removed?

Same is true for the UndoCommand.java, but I can't comment on that line.

2018-10-07 08:06 UTC, LXGaming commented on src/main/java/com/helion3/prism/api/records/BlockResult.java
>  import org.spongepowered.api.world.BlockChangeFlag;
Done

2018-10-08 17:38 UTC, viveleroi commented on src/main/java/com/helion3/prism/api/records/PrismRecord.java
> -            if (position.isPresent()) {
Can you clarify why you dropped location data? That seems essential for items.

2018-10-08 19:50 UTC, LXGaming commented on src/main/java/com/helion3/prism/api/records/PrismRecord.java
> -            if (position.isPresent()) {
The location is set inside the `dropped` and `pickedUp` methods, The reason behind this is the Transaction doesn't have Location information instead I'm grabbing it from the source.

2018-10-12 17:01 UTC, merged