Storage Improvements
prism/PrismSponge pull request #114
Opened 2018-10-16 00:06 UTC by LXGaming

Relocate mongodb and bson
Add configurable pool sizes
Setup Hikari for H2
Add SQL purging
Fix Mongo Deprecated method

Should fix #109 as H2 should now have multiple connections.

2018-10-16 00:52 UTC, viveleroi requested changes

2018-10-16 00:52 UTC, viveleroi commented on src/main/java/com/helion3/prism/storage/mysql/MySQLStorageAdapter.java
> +    protected int purgeExtra() throws Exception {
This method (for both MySQL and H2 variations) shouldn't be required because the create table sql has a foreign key/delete cascade statements:

- [H2](https://github.com/prism/Prism/blob/master/src/main/java/com/helion3/prism/storage/h2/H2StorageAdapter.java#L105-L107)
- [MySQL](https://github.com/prism/Prism/blob/master/src/main/java/com/helion3/prism/storage/mysql/MySQLStorageAdapter.java#L124-L126)

If the primary record is deleted it should automatically delete the extra records.

2018-10-19 05:54 UTC, LXGaming commented on src/main/java/com/helion3/prism/storage/mysql/MySQLStorageAdapter.java
> +    protected int purgeExtra() throws Exception {
Ah, Good point

2018-10-19 16:53 UTC, viveleroi approved these changes

2018-10-19 16:53 UTC, viveleroi commented
Looks fine, have you been able to test the changes, primarily the purge logic?

2018-10-21 00:06 UTC, LXGaming commented
I've tested the purge logic on H2 and MySQL with databases between 50 ~ 100mb in size (About 200000 rows) works without issues

2018-10-22 18:17 UTC, merged